spring:
  application:
    name: Mentor-Dual-Selection-System

  # Configure MySQL data source
  datasource:
    url: jdbc:mysql://223.82.75.77:3308/teacherselectionsystem?useSSL=false&serverTimezone=UTC
    username: root
    password: CL9zbYfqH1ZYShPO
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Auto-create and update tables
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  # Exclude specific autoconfiguration
  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration
  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true  # Cookie

  # Multipart file upload settings
  servlet:
    multipart:
      max-file-size: 100MB  # 设置单个文件上传的最大大小为 100MB
      max-request-size: 100MB  # 设置整个请求的最大大小为 100MB

  mail:
    host: smtp.exmail.qq.com  # 腾讯企业邮箱 SMTP 服务器地址
    port: 465                 # SMTP 端口号
    username: shendekoudai@lovelumine.com  # 你的邮箱账户
    password: ouyangZHUO088741!            # 你的邮箱密码
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

# Application port
server:
  port: 50000

# Knife4j configuration

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: mentordualselectionsystem.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: Copyright © 2023-2024 Yongxin County Lovelumine Technology Co., Ltd.
debug: true

# MinIO Configuration
minio:
  url: https://minio.lumoxuan.cn  # MinIO server URL
  access-key: uv9Ey4hCgAeF9US8IvW7  # MinIO access key
  secret-key: EJxNuc7hJId6cW969JXcMtd14xs7d9wTmC17Mn5W  # MinIO secret key
  bucket-name: mentor-dual-selection-system  # default bucket name, can be customized
